version: "3"

services:
  gilder-notify-api:
    image: node:16-buster
    command: bash -c "npm install && npm install sqlite3 && npm start"
    working_dir: /gilder-notify
    volumes: 
      - ./dist/api:/gilder-notify
    ports:
      - "3000:3000"
  gilder-listen:
    image: node:16-buster
    command: bash -c "npm install && npm install -g supervisor && supervisor ./gilder-realm-listen/realmListener.js"
    working_dir: /gilder-notify
    volumes: 
      - ./dist/listen:/gilder-notify
