version: "3"

services:
  gilder-notify:
    image: node:16-buster
    command: bash -c "npm install && npm install -g typescript ts-node supervisor && tsc -p ./tsconfig.json && $(supervisor ./dist/gilder-realm-listen/realmListener.js &) && cd api && npm install && nest start"
    working_dir: /gilder-notify
    volumes: 
      - ./:/gilder-notify
    ports:
      - "3000:3000"
